- firewalld:
    port: 21/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 22/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 53/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 123/tcp
    permanent: true
    state: enabled

- firewalld:
    port: 53/udp
    permanent: true
    state: enabled

- include: centos7.yml
  when: ansible_all_ipv4_addresses == "105.0.5.102"
  
- include: centos7b.yml
  when: ansible_all_ipv4_addresses == "105.0.5.103"
