- name: Install mtr
  package:
    name: mtr
    state: latest
  tags: packages

- name: Install tcpdump
  package:
    name: tcpdump
    state: latest
  tags: packages

- name:	Install nano
  package:     
    name: nano
    state: latest
  tags:	packages

# Added these so that the DNS servers could be added
- name: Install NetworkManager (Debian)
  package:
    name: network-manager
    state: latest
  tags: packages
  when: ansible_os_family == "Debian"

- name: Install NetworkManager (CentOS)
  package:
    name: NetworkManager-glib
    state: latest
  tags: packages
  when: ansible_os_family == "RedHat"
